=  Local Volunteer Community Support Portal website For Everyone COME & LEARN.

== Introduction

:helpgroup: https://www.facebook.com/groups/212831576624482/[Zurich Coronavirus Help Group]

In the context of the {helpgroup} it was identified the need to have a web site that can be easily used for the local general community contact within Switzerland. The goal is for people that might need help to easily locate people that is available to help them from the nearast location. With this approach we decrease the distribution/risk of contagium, and protect the group of people that is more vulnerable to the Covid19 oubtreak.

== How to run

```bash
git clone https://github.com/ViralHelp/website
cd website
pip install --user -r requirements.txt

# Open two terminals

# Run the www on one terminal
scripts/start_www.sh

# Run the api on another terminal
scripts/start_api.sh

```

== How to test (www)

For regular use, browse http://en.localhost:8080

For testing the help provider join controller:
```sh
curl "http://en.localhost:8080/provider/join?email=YOUR_EMAIL&token=YOUR_TOKEN"
```

== How to test (api)
curl http://localhost:9090/provider/login -d "email=EMAIL_ADDRESS&lang=en"


== Desired Features are following:-

. Simple interface to be usable by elder people
. Multilanguage support for the site structure
. Ability for support providers to register
.. spoken languages
.. covering regions
.. support category ? (Grosseries/Pharmacy/Others?)
. Ability for support seeker to create aid requests
.. Filtering by spoken language
. Filtering by postal code

NOTE: Using geolocation would be more efficient for locating nearest people, should be evaluated once we have a minimal working version with post codes

